// TecnoMart Chatbot Knowledge & Laptop Catalog
// Real inventory data matching TecnoMart Hyderabad storefront

export const TECNOMART_CHATBOT_INFO = {
  storeName: "TecnoMart",
  legalName: "Tecno Mart Technologies Private Limited",
  phone: "+91 98663 88870",
  whatsappPhone: "919866388870",
  address: "7 Tombs Rd, Raghava Colony, Neeraj Colony, Tolichowki, Hyderabad, 500008",
  hours: "10:30 AM – 9:30 PM (Mon - Sun)",
  experienceYears: "Since 2016",
  uspList: [
    "Grade-A+ Refurbished with 1-Year Store Warranty",
    "32-point comprehensive hardware check",
    "Same-day doorstep delivery & setup in Hyderabad",
    "Instant WhatsApp live video call inspection",
    "GST Invoice with official warranty on all items"
  ]
};

export const CHATBOT_FEATURED_LAPTOPS = [
  {
    id: "rec-hp-elitebook-840",
    slug: "hp-elitebook-840-g7",
    name: "HP EliteBook 840 G7 Ultrabook",
    brand: "HP",
    condition: "Certified Refurbished (Grade A+)",
    conditionBadge: "Refurbished",
    processor: "Intel Core i5-10310U (vPro)",
    ram: "16GB DDR4",
    storage: "512GB NVMe SSD",
    display: "14\" FHD Anti-Glare IPS",
    battery: "Up to 8 hrs backup",
    price: "₹32,999",
    originalPrice: "₹89,990",
    rawPrice: 32999,
    discountPercent: "63% OFF",
    warranty: "1 Year TecnoMart Warranty",
    availability: "In Stock (Hyderabad Store)",
    image: "/webp/landing/asus-zenbook-ultrabook-charcoal.webp",
    badges: ["Best for Students & Office", "1-Yr Warranty"],
    category: "refurbished",
    rating: 4.8,
    reviews: 64,
    bestFor: ["study", "office", "coding", "general"]
  },
  {
    id: "rec-dell-latitude-7400",
    slug: "dell-latitude-7400",
    name: "Dell Latitude 7400 Slim Business Laptop",
    brand: "Dell",
    condition: "Certified Refurbished (Grade A+)",
    conditionBadge: "Refurbished",
    processor: "Intel Core i5-8365U Quad-Core",
    ram: "16GB DDR4",
    storage: "256GB NVMe SSD",
    display: "14\" FHD Anti-Glare",
    battery: "Up to 7 hrs backup",
    price: "₹28,999",
    originalPrice: "₹79,900",
    rawPrice: 28999,
    discountPercent: "63% OFF",
    warranty: "1 Year TecnoMart Warranty",
    availability: "In Stock (Hyderabad Store)",
    image: "/webp/landing/asus-zenbook-ultrabook-charcoal.webp",
    badges: ["Under ₹30K", "1-Yr Warranty"],
    category: "refurbished",
    rating: 4.7,
    reviews: 52,
    bestFor: ["study", "office", "general"]
  },
  {
    id: "rec-lenovo-thinkpad-t490",
    slug: "lenovo-thinkpad-t490",
    name: "Lenovo ThinkPad T490 Rugged Business",
    brand: "Lenovo",
    condition: "Certified Refurbished (Grade A+)",
    conditionBadge: "Refurbished",
    processor: "Intel Core i5-8365U Quad-Core",
    ram: "16GB RAM",
    storage: "256GB NVMe SSD",
    display: "14\" FHD IPS Matte",
    battery: "6-8 hrs backup",
    price: "₹24,999",
    originalPrice: "₹74,999",
    rawPrice: 24999,
    discountPercent: "66% OFF",
    warranty: "1 Year TecnoMart Warranty",
    availability: "In Stock (Limited units)",
    image: "/webp/laptops/asus-rog-zephyrus-g16-front.webp",
    badges: ["Under ₹25K", "Military-Grade Tough"],
    category: "refurbished",
    rating: 4.8,
    reviews: 42,
    bestFor: ["study", "office", "general"]
  },
  {
    id: "rec-lenovo-thinkpad-t480",
    slug: "lenovo-thinkpad-t480",
    name: "Lenovo ThinkPad T480 Dual-Battery Edition",
    brand: "Lenovo",
    condition: "Certified Refurbished (Grade A+)",
    conditionBadge: "Refurbished",
    processor: "Intel Core i5-8250U",
    ram: "16GB RAM",
    storage: "512GB SSD",
    display: "14\" FHD IPS",
    battery: "Hot-swappable dual battery",
    price: "₹22,999",
    originalPrice: "₹68,000",
    rawPrice: 22999,
    discountPercent: "66% OFF",
    warranty: "1 Year TecnoMart Warranty",
    availability: "In Stock",
    image: "/webp/laptops/asus-rog-zephyrus-g16-front.webp",
    badges: ["Best Budget Pick", "1-Yr Warranty"],
    category: "refurbished",
    rating: 4.8,
    reviews: 80,
    bestFor: ["study", "office", "general"]
  },
  {
    id: "rec-dell-latitude-5410",
    slug: "dell-latitude-5410",
    name: "Dell Latitude 5410 Corporate Edition",
    brand: "Dell",
    condition: "Certified Refurbished (Grade A+)",
    conditionBadge: "Refurbished",
    processor: "Intel Core i5-10310U (10th Gen)",
    ram: "16GB DDR4",
    storage: "512GB NVMe SSD",
    display: "14\" FHD IPS",
    battery: "Up to 8 hrs backup",
    price: "₹34,999",
    originalPrice: "₹82,000",
    rawPrice: 34999,
    discountPercent: "57% OFF",
    warranty: "1 Year TecnoMart Warranty",
    availability: "In Stock (Tolichowki)",
    image: "/webp/landing/asus-zenbook-ultrabook-charcoal.webp",
    badges: ["Fast DDR4", "1-Yr Warranty"],
    category: "refurbished",
    rating: 4.8,
    reviews: 35,
    bestFor: ["study", "office", "coding"]
  },
  {
    id: "rec-hp-probook-440",
    slug: "hp-probook-440-g8",
    name: "HP ProBook 440 G8 Aluminum Thin & Light",
    brand: "HP",
    condition: "Certified Refurbished (Grade A+)",
    conditionBadge: "Refurbished",
    processor: "Intel Core i5-1135G7 (11th Gen Iris Xe)",
    ram: "16GB DDR4",
    storage: "512GB NVMe SSD",
    display: "14\" FHD Micro-Edge IPS",
    battery: "Up to 9 hrs backup",
    price: "₹38,999",
    originalPrice: "₹85,000",
    rawPrice: 38999,
    discountPercent: "54% OFF",
    warranty: "1 Year TecnoMart Warranty",
    availability: "In Stock",
    image: "/webp/landing/asus-zenbook-ultrabook-charcoal.webp",
    badges: ["Iris Xe Graphics", "1-Yr Warranty"],
    category: "refurbished",
    rating: 4.8,
    reviews: 48,
    bestFor: ["study", "coding", "office"]
  },
  {
    id: "rec-lenovo-thinkpad-l14",
    slug: "lenovo-thinkpad-l14-gen2",
    name: "Lenovo ThinkPad L14 Gen 2 (Ryzen 5)",
    brand: "Lenovo",
    condition: "Certified Refurbished (Grade A+)",
    conditionBadge: "Refurbished",
    processor: "AMD Ryzen 5 5650U PRO (6 Cores / 12 Threads)",
    ram: "16GB DDR4",
    storage: "512GB NVMe SSD",
    display: "14\" FHD Anti-Glare",
    battery: "Up to 10 hrs backup",
    price: "₹43,999",
    originalPrice: "₹89,900",
    rawPrice: 43999,
    discountPercent: "51% OFF",
    warranty: "1 Year TecnoMart Warranty",
    availability: "In Stock (Tolichowki Hub)",
    image: "/webp/laptops/asus-rog-zephyrus-g16-front.webp",
    badges: ["6-Core Ryzen PRO", "1-Yr Warranty"],
    category: "refurbished",
    rating: 4.9,
    reviews: 58,
    bestFor: ["coding", "office", "design"]
  },
  {
    id: "rec-dell-latitude-7420",
    slug: "dell-latitude-7420-carbon",
    name: "Dell Latitude 7420 Carbon Fiber Ultrabook",
    brand: "Dell",
    condition: "Certified Refurbished (Grade A+)",
    conditionBadge: "Refurbished",
    processor: "Intel Core i7-1185G7 (11th Gen vPro)",
    ram: "16GB LPDDR4x",
    storage: "512GB Gen4 NVMe SSD",
    display: "14\" FHD Super Low Power 400 nits",
    battery: "Up to 11 hrs backup",
    price: "₹47,999",
    originalPrice: "₹1,15,000",
    rawPrice: 47999,
    discountPercent: "58% OFF",
    warranty: "1 Year TecnoMart Warranty",
    availability: "In Stock (Tolichowki)",
    image: "/webp/landing/asus-zenbook-ultrabook-charcoal.webp",
    badges: ["Core i7 vPro", "1-Yr Warranty"],
    category: "refurbished",
    rating: 4.9,
    reviews: 62,
    bestFor: ["coding", "office", "design"]
  },
  {
    id: "rec-lenovo-thinkpad-t14s",
    slug: "refurbished-lenovo-thinkpad-t14s",
    name: "Certified Refurbished ThinkPad T14s Gen 3",
    brand: "Lenovo",
    condition: "Certified Refurbished (Grade A+)",
    conditionBadge: "Refurbished",
    processor: "AMD Ryzen 7 PRO 6850U (8C/16T)",
    ram: "16GB LPDDR5",
    storage: "512GB NVMe SSD",
    display: "14\" WUXGA (1920x1200) Low Power",
    battery: "Up to 12 hrs battery life",
    price: "₹52,999",
    originalPrice: "₹1,24,990",
    rawPrice: 52999,
    discountPercent: "58% OFF",
    warranty: "1 Year TecnoMart Warranty",
    availability: "In Stock",
    image: "/webp/refurbished/refurbished-lenovo-thinkpad-t14s.webp",
    badges: ["8-Core Ryzen 7 PRO", "1-Yr Warranty"],
    category: "refurbished",
    rating: 4.9,
    reviews: 140,
    bestFor: ["coding", "design", "office"]
  },
  {
    id: "rec-macbook-air-m1",
    slug: "refurbished-macbook-air-m1",
    name: "Apple MacBook Air 13\" (M1 Chip)",
    brand: "Apple",
    condition: "Certified Refurbished (Grade A+)",
    conditionBadge: "Refurbished",
    processor: "Apple M1 Chip (8-Core CPU)",
    ram: "8GB Unified Memory",
    storage: "256GB PCIe SSD",
    display: "13.3\" Retina True Tone",
    battery: "15+ hrs battery (100% health tested)",
    price: "₹54,990",
    originalPrice: "₹99,900",
    rawPrice: 54990,
    discountPercent: "45% OFF",
    warranty: "1 Year TecnoMart Warranty",
    availability: "In Stock (Tolichowki Hub)",
    image: "/webp/landing/apple-macbook-air-silver-open.webp",
    badges: ["Student Favorite", "Silent & Slim"],
    category: "refurbished",
    rating: 4.9,
    reviews: 240,
    bestFor: ["study", "coding", "design", "office"]
  },
  {
    id: "rec-hp-victus-15",
    slug: "hp-victus-15-gaming",
    name: "HP Victus 15 Gaming Laptop",
    brand: "HP",
    condition: "Brand New Sealed Box",
    conditionBadge: "Brand New",
    processor: "Intel Core i5-13420H (13th Gen)",
    ram: "16GB DDR4",
    storage: "512GB Gen4 SSD",
    display: "15.6\" 144Hz FHD IPS",
    graphics: "NVIDIA GeForce RTX 3050 (6GB)",
    battery: "Fast Charging 50% in 30 mins",
    price: "₹69,990",
    originalPrice: "₹82,990",
    rawPrice: 69990,
    discountPercent: "16% OFF",
    warranty: "1 Year Official Brand Warranty + GST Bill",
    availability: "In Stock (Ready to dispatch)",
    image: "/webp/landing/asus-tuf-gaming-laptop-front.webp",
    badges: ["Gaming & 3D Render", "RTX 3050 6GB"],
    category: "new",
    rating: 4.7,
    reviews: 188,
    bestFor: ["gaming", "coding", "design"]
  },
  {
    id: "rec-asus-tuf-a15",
    slug: "asus-tuf-gaming-a15",
    name: "ASUS TUF Gaming A15 (RTX 4050)",
    brand: "ASUS",
    condition: "Brand New Sealed Box",
    conditionBadge: "Brand New",
    processor: "AMD Ryzen 7 7735HS (8 Cores, 16 Threads)",
    ram: "16GB DDR5 4800MHz",
    storage: "512GB Gen4 NVMe SSD",
    display: "15.6\" 144Hz FHD IPS",
    graphics: "NVIDIA GeForce RTX 4050 6GB (140W TGP)",
    battery: "90Wh massive battery",
    price: "₹74,990",
    originalPrice: "₹89,990",
    rawPrice: 74990,
    discountPercent: "17% OFF",
    warranty: "1 Year Official Brand Warranty + GST Bill",
    availability: "In Stock (Hyderabad Store)",
    image: "/webp/landing/asus-tuf-gaming-laptop-front.webp",
    badges: ["RTX 4050 140W", "Military-Grade Tough"],
    category: "new",
    rating: 4.8,
    reviews: 350,
    bestFor: ["gaming", "coding", "design"]
  },
  {
    id: "rec-macbook-air-m2",
    slug: "apple-macbook-air-13-m2",
    name: "Apple MacBook Air 13\" (M2 Chip)",
    brand: "Apple",
    condition: "Brand New Sealed Box",
    conditionBadge: "Brand New",
    processor: "Apple M2 (8-core CPU, 8-core GPU)",
    ram: "8GB Unified Memory",
    storage: "256GB High-Speed SSD",
    display: "13.6\" Liquid Retina Display",
    battery: "18 hrs all-day battery",
    price: "₹89,900",
    originalPrice: "₹99,900",
    rawPrice: 89900,
    discountPercent: "10% OFF",
    warranty: "1 Year Apple India Warranty + GST Bill",
    availability: "In Stock (Tolichowki)",
    image: "/webp/laptops/apple-macbook-air-15-m3-front.webp",
    badges: ["Apple M2 Chip", "Liquid Retina"],
    category: "new",
    rating: 4.9,
    reviews: 890,
    bestFor: ["study", "coding", "design", "office"]
  },
  {
    id: "rec-macbook-pro-14-m1-pro",
    slug: "refurbished-macbook-pro-14-m1-pro",
    name: "Apple MacBook Pro 14\" (M1 Pro)",
    brand: "Apple",
    condition: "Certified Refurbished (Grade A+)",
    conditionBadge: "Refurbished",
    processor: "Apple M1 Pro (8-Core CPU, 14-Core GPU)",
    ram: "16GB Unified",
    storage: "512GB High-speed SSD",
    display: "14.2\" Liquid Retina XDR 120Hz",
    battery: "12-14 hrs battery life",
    price: "₹92,990",
    originalPrice: "₹1,94,900",
    rawPrice: 92990,
    discountPercent: "52% OFF",
    warranty: "1 Year TecnoMart Warranty",
    availability: "In Stock",
    image: "/webp/refurbished/refurbished-apple-macbook-pro-14-m1.webp",
    badges: ["4K Video Editing", "XDR 120Hz ProMotion"],
    category: "refurbished",
    rating: 4.9,
    reviews: 78,
    bestFor: ["design", "coding", "office"]
  }
];

// Initial conversation suggestions / smart quick actions
export const INITIAL_QUICK_ACTIONS = [
  { id: "find-laptop", label: "Find a Laptop", action: "find_laptop", category: "primary" },
  { id: "browse-refurbished", label: "Browse Refurbished", action: "browse_refurbished", category: "primary" },
  { id: "browse-new", label: "Browse New Laptops", action: "browse_new", category: "primary" },
  { id: "check-availability", label: "Check Availability", action: "check_stock", category: "secondary" },
  { id: "talk-support", label: "Talk to Support", action: "talk_support", category: "support" }
];

export const BUDGET_OPTIONS = [
  { id: "under-30k", label: "Under ₹30,000", max: 30000, min: 0 },
  { id: "30k-40k", label: "₹30,000 - ₹40,000", max: 40000, min: 30000 },
  { id: "40k-50k", label: "₹40,000 - ₹50,000", max: 50000, min: 40000 },
  { id: "50k-70k", label: "₹50,000 - ₹70,000", max: 70000, min: 50000 },
  { id: "above-70k", label: "Above ₹70,000", max: Infinity, min: 70000 }
];

export const USE_CASE_OPTIONS = [
  { id: "study", label: "Study & College", icon: "BookOpen" },
  { id: "office", label: "Office & Productivity", icon: "Briefcase" },
  { id: "coding", label: "Coding & Development", icon: "Code2" },
  { id: "design", label: "Design & Video Editing", icon: "Palette" },
  { id: "gaming", label: "Gaming", icon: "Gamepad2" },
  { id: "general", label: "General Everyday Use", icon: "Laptop" }
];
